[package]
name = "comix"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"         # Optional, defaults to "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "comix"

[dependencies]
chumsky = "0.9"
